-- Supabase Dashboard > SQL Editor에서 한 번 실행하세요.

create table if not exists public.area_status (
    province text not null,
    subregion text not null,
    status text not null default '미방문'
        check (status in ('가본 곳', '가고 싶은 곳', '미방문')),
    updated_at timestamptz not null default now(),
    primary key (province, subregion)
);

create table if not exists public.places (
    id bigint generated by default as identity primary key,
    legacy_sqlite_id bigint unique,
    region text not null,
    city text not null,
    place_name text not null,
    category text not null,
    visit_date date,
    rating integer not null default 3 check (rating between 1 and 5),
    one_line_review text not null,
    latitude double precision not null check (latitude between 32 and 39.5),
    longitude double precision not null check (longitude between 124 and 132),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_places_region_city
    on public.places (region, city);
create index if not exists idx_places_visit_date
    on public.places (visit_date desc);

-- 브라우저에서 직접 접근하는 공개 앱이 아니라 Streamlit 서버가 Secret key로 접근합니다.
-- 따라서 RLS를 켜고 anon/authenticated 역할에는 정책을 만들지 않습니다.
alter table public.area_status enable row level security;
alter table public.places enable row level security;

revoke all on table public.area_status from anon, authenticated;
revoke all on table public.places from anon, authenticated;
revoke usage, select on sequence public.places_id_seq from anon, authenticated;
